### ISSUE TITLE
WebStorm

### ISSUE THREAD

**Issue by KyleBing** [jiaolong1021/ElementPlugin#10]
```bash
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  206 != 215
  which is length of [rate_src_main={}, el-cascader-panel={}, input_number={}, el-upload={}, upload={}, el-spinner={}, el-tooltip={}, el-slider={}, bar={}, el-icon={}, src_tree={}, carousel_src_main={}, el-option={}, footer_src_main={}, el-date-picker={}, el-skeleton-item={}, el-checkbox-group={}, el-color-picker={}, el-marker={}, el-breadcrumb={}, el-popover={}, dropdown={}, input={}, el-badge={}, date-table={}, tab_pane={}, cascader-node={}, el-dialog={}, el-backtop={}, el-table-column={}, el-color-alpha-slider={}, alert_src_main={}, el-carousel-item={}, el-radio-group={}, icon={}, el-popconfirm={}, el-image-viewer={}, switch_src_component={}, src_component={}, breadcrumb_item={}, el-sl-panel={}, el-calendar={}, el-switch={}, el-menu-item-group={}, card_src_main={}, time-range={}, component={}, el-upload-list={}, menu_item_group={}, form_item={}, progress={}, el-timeline={}, el-color-picker-dropdown={}, tab-bar={}, el-empty={}, empty_src={}, el-skeleton={}, el-select={}, el-input={}, migrating={}, spinner={}, el-input-number={}, el-image={}, el-timeline-item={}, radio_group={}, header_src_main={}, el-collapse-item={}, el-carousel={}, el-link={}, el-pagination={}, el-aside={}, el-tree-node={}, time-spinner={}, popconfirm_src_main={}, checkbox_button={}, el-button-group={}, el-scrollbar={}, el-transfer-panel={}, el-radio-button={}, el-cascader={}, locale={}, time-select={}, el-time-select={}, el-steps={}, el-color-hue-slider={}, option_group={}, el-main={}, el-rate={}, el-alert={}, el-tree={}, el-select-dropdown={}, el-divider={}, aside_src_main={}, month-range={}, img-empty={}, date-range={}, image_src_main={}, el-checkbox={}, backtop_src_main={}, skeleton_src={}, timeline_src_main={}, step={}, el-step={}, time={}, skeleton_src_item={}, el-container={}, el-progress={}, el-table-header={}, el-pager={}, el-menu={}, menu_item={}, src_table={}, el-dropdown={}, badge_src_main={}, cascader={}, avatar_src_main={}, el-tag={}, el-table-footer={}, main_src_main={}, el-time-picker={}, item={}, autocomplete-suggestions={}, index={}, el-checkbox-button={}, src_tag={}, upload_src={}, divider_src_main={}, src_button={}, submenu={}, el-tabs={}, src_form={}, el-col={}, el-card={}, el-button={}, el-form-item={}, el-table-body={}, timeline_src_item={}, el-drawer={}, tabs={}, src_select={}, link_src_main={}, el-footer={}, table={}, el-option-group={}, el-submenu={}, el-radio={}, el-page-header={}, transfer_src_main={}, el-row={}, el-avatar={}, menu={}, label-wrap={}, el-tab-pane={}, img-placeholder={}, button_group={}, slider_src_main={}, predefine={}, el-autocomplete={}, el-table={}, src_radio={}, date={}, el-dropdown-menu={}, el-collapse={}, src_item={}, main={}, src_input={}, vue-popper={}, radio_button={}, calendar_src_main={}, container_src_main={}, color_picker_src_main={}, dropdown_item={}, tag={}, picker={}, collapse_item={}, tree={}, menu-mixin={}, element-ui.common={}, steps={}, el-menu-item={}, el-transfer={}, src_checkbox={}, page_header_src_main={}, el-header={}, emitter={}, tab-nav={}, cascader_panel={}, month-table={}, el-cascader-menu={}, src_menu={}, drawer_src_main={}, dropdown_menu={}, year-table={}, el-dropdown-item={}, el-breadcrumb-item={}, el-form={}, src={}, autocomplete={}, el-collapse-transition={}, el-upload-drag={}, breadcrumb={}, checkbox_group={}, src_option={}, el-table-filter-panel={}, el-slider-button={}, collapse={}] and [rate_src_main={}, el-cascader-panel={}, input_number={}, el-upload={}, upload={}, el-spinner={}, el-tooltip={}, el-slider={}, bar={}, el-icon={}, src_tree={}, carousel_src_main={}, el-option={}, footer_src_main={}, el-date-picker={}, el-skeleton-item={}, el-checkbox-group={}, el-color-picker={}, el-marker={}, el-breadcrumb={}, el-popover={}, dropdown={}, input={}, el-badge={}, date-table={}, tab_pane={}, cascader-node={}, el-dialog={}, src_main={}, el-backtop={}, el-table-column={}, el-color-alpha-slider={}, alert_src_main={}, el-carousel-item={}, el-radio-group={}, icon={}, el-popconfirm={}, table_column={}, el-image-viewer={}, switch_src_component={}, src_component={}, breadcrumb_item={}, el-sl-panel={}, el-calendar={}, el-switch={}, el-menu-item-group={}, card_src_main={}, time-range={}, component={}, el-upload-list={}, menu_item_group={}, form_item={}, progress={}, el-timeline={}, el-color-picker-dropdown={}, tab-bar={}, el-empty={}, empty_src={}, el-skeleton={}, el-select={}, el-input={}, migrating={}, spinner={}, el-input-number={}, el-image={}, el-timeline-item={}, radio_group={}, header_src_main={}, el-collapse-item={}, el-carousel={}, el-link={}, el-pagination={}, el-aside={}, el-tree-node={}, time-spinner={}, popconfirm_src_main={}, date_picker={}, checkbox_button={}, el-button-group={}, el-scrollbar={}, pagination={}, el-transfer-panel={}, el-radio-button={}, el-cascader={}, locale={}, time-select={}, el-time-select={}, el-steps={}, el-color-hue-slider={}, option_group={}, el-main={}, el-rate={}, el-alert={}, el-tree={}, el-select-dropdown={}, el-divider={}, aside_src_main={}, month-range={}, img-empty={}, date-range={}, image_src_main={}, el-checkbox={}, backtop_src_main={}, skeleton_src={}, timeline_src_main={}, step={}, el-step={}, time={}, skeleton_src_item={}, el-container={}, el-progress={}, el-table-header={}, el-pager={}, el-menu={}, menu_item={}, src_table={}, el-dropdown={}, badge_src_main={}, cascader={}, avatar_src_main={}, el-tag={}, el-table-footer={}, main_src_main={}, el-time-picker={}, item={}, autocomplete-suggestions={}, index={}, el-checkbox-button={}, src_tag={}, upload_src={}, divider_src_main={}, src_button={}, submenu={}, el-tabs={}, src_form={}, el-col={}, el-card={}, el-button={}, el-form-item={}, el-table-body={}, timeline_src_item={}, el-drawer={}, tabs={}, src_select={}, link_src_main={}, el-footer={}, table={}, el-option-group={}, el-submenu={}, el-radio={}, el-page-header={}, transfer_src_main={}, src_row={}, el-avatar={}, menu={}, label-wrap={}, el-tab-pane={}, img-placeholder={}, button_group={}, slider_src_main={}, predefine={}, el-autocomplete={}, el-table={}, src_radio={}, time_picker={}, date={}, col={}, el-dropdown-menu={}, el-collapse={}, src_item={}, main={}, src_input={}, vue-popper={}, radio_button={}, calendar_src_main={}, container_src_main={}, color_picker_src_main={}, dropdown_item={}, tag={}, picker={}, collapse_item={}, tree={}, menu-mixin={}, element-ui.common={}, steps={}, el-menu-item={}, el-transfer={}, src_checkbox={}, page_header_src_main={}, el-header={}, emitter={}, tab-nav={}, cascader_panel={}, month-table={}, el-cascader-menu={}, src_menu={}, drawer_src_main={}, el-row={}, dropdown_menu={}, year-table={}, el-dropdown-item={}, el-breadcrumb-item={}, scrollbar_src_main={}, el-form={}, src={}, autocomplete={}, el-collapse-transition={}, el-upload-drag={}, picker_time_select={}, breadcrumb={}, checkbox_group={}, src_option={}, el-table-filter-panel={}, el-slider-button={}, collapse={}]

Recomputation gives com.intellij.util.CachedValueBase$Data@520f26b3 which is equivalent to 'fresh'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:89)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:76)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.jetbrains.vuejs.model.source.VueSourcePlugin.getComponents(VueSourcePlugin.kt:35)
	at org.jetbrains.vuejs.model.VueGlobalImpl.buildElementToParentMap(VueGlobalImpl.kt:70)
	at org.jetbrains.vuejs.model.VueGlobalImpl.access$buildElementToParentMap(VueGlobalImpl.kt:24)
	at org.jetbrains.vuejs.model.VueGlobalImpl$getElementToParentMap$1.compute(VueGlobalImpl.kt:45)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.jetbrains.vuejs.model.VueGlobalImpl.getElementToParentMap(VueGlobalImpl.kt:44)
	at org.jetbrains.vuejs.model.VueGlobalImpl.access$getElementToParentMap(VueGlobalImpl.kt:24)
	at org.jetbrains.vuejs.model.VueGlobalImpl$Companion.getParents(VueGlobalImpl.kt:102)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.getParents(VueSourceContainer.kt:18)
	at org.jetbrains.vuejs.model.VueScopeElement$DefaultImpls.acceptEntities(VueScopeElement.kt:34)
	at org.jetbrains.vuejs.model.VueEntitiesContainer$DefaultImpls.acceptEntities(VueEntitiesContainer.kt)
	at org.jetbrains.vuejs.model.VueContainer$DefaultImpls.acceptEntities(VueContainer.kt)
	at org.jetbrains.vuejs.model.source.VueSourceContainer.acceptEntities(VueSourceContainer.kt:13)
	at org.jetbrains.vuejs.web.VueWebSymbolsAdditionalContextProvider$EntityContainerWrapper.getSymbols(VueWebSymbolsAdditionalContextProvider.kt:138)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1$1.invoke(WebSymbolsRegistryImpl.kt:67)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1$1.invoke(WebSymbolsRegistryImpl.kt:12)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1.invoke(WebSymbolsRegistryImpl.kt:71)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1.invoke(WebSymbolsRegistryImpl.kt:12)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runQuery$2.compute(WebSymbolsRegistryImpl.kt:148)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runQuery$2.compute(WebSymbolsRegistryImpl.kt:12)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runQuery(WebSymbolsRegistryImpl.kt:132)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runNameMatchQuery$intellij_javascript_web(WebSymbolsRegistryImpl.kt:62)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runNameMatchQuery(WebSymbolsRegistryImpl.kt:38)
	at com.intellij.javascript.web.symbols.WebSymbolsRegistry.runNameMatchQuery(WebSymbolsRegistry.kt:19)
	at com.intellij.javascript.web.webTypes.json.WebTypesJsonUtilsKt.resolve(WebTypesJsonUtils.kt:98)
	at com.intellij.javascript.web.webTypes.json.WebTypesJsonUtilsKt.resolve$default(WebTypesJsonUtils.kt:94)
	at com.intellij.javascript.web.webTypes.patterns.ComplexPattern$PatternItemsProvider$matchName$1.invoke(ComplexPattern.kt:344)
	at com.intellij.javascript.web.webTypes.patterns.ComplexPattern$PatternItemsProvider$matchName$1.invoke(ComplexPattern.kt:336)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.intellij.javascript.web.webTypes.patterns.ComplexPattern$PatternItemsProvider.matchName(ComplexPattern.kt:352)
	at com.intellij.javascript.web.webTypes.patterns.ItemPattern.match$intellij_javascript_web(ItemPattern.kt:23)
	at com.intellij.javascript.web.webTypes.patterns.ComplexPattern.performPatternMatch(ComplexPattern.kt:218)
	at com.intellij.javascript.web.webTypes.patterns.ComplexPattern.access$performPatternMatch(ComplexPattern.kt:12)
	at com.intellij.javascript.web.webTypes.patterns.ComplexPattern$match$1.invoke(ComplexPattern.kt:41)
	at com.intellij.javascript.web.webTypes.patterns.ComplexPattern$match$1.invoke(ComplexPattern.kt:12)
	at com.intellij.javascript.web.webTypes.patterns.ComplexPattern.process(ComplexPattern.kt:190)
	at com.intellij.javascript.web.webTypes.patterns.ComplexPattern.match$intellij_javascript_web(ComplexPattern.kt:39)
	at com.intellij.javascript.web.webTypes.patterns.WebTypesPattern.match(WebTypesPattern.kt:87)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase$ContributionsMap.getMatchedContributions(WebTypesSymbolsContainerBase.kt:339)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase$ContributionsMap.access$getMatchedContributions(WebTypesSymbolsContainerBase.kt:208)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase$ContributionsMap$collectPatternContributions$1.invoke(WebTypesSymbolsContainerBase.kt:311)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase$ContributionsMap$collectPatternContributions$1.invoke(WebTypesSymbolsContainerBase.kt:208)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase$ContributionsMap.collectPatternContributions(WebTypesSymbolsContainerBase.kt:316)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase$ContributionsMap.getContributions(WebTypesSymbolsContainerBase.kt:262)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase$getSymbols$1.invoke(WebTypesSymbolsContainerBase.kt:65)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase$getSymbols$1.invoke(WebTypesSymbolsContainerBase.kt:28)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.intellij.javascript.web.webTypes.WebTypesSymbolsContainerBase.getSymbols(WebTypesSymbolsContainerBase.kt:66)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1$1.invoke(WebSymbolsRegistryImpl.kt:67)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1$1.invoke(WebSymbolsRegistryImpl.kt:12)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1.invoke(WebSymbolsRegistryImpl.kt:71)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runNameMatchQuery$1.invoke(WebSymbolsRegistryImpl.kt:12)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runQuery$2.compute(WebSymbolsRegistryImpl.kt:148)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl$runQuery$2.compute(WebSymbolsRegistryImpl.kt:12)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runQuery(WebSymbolsRegistryImpl.kt:132)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runNameMatchQuery$intellij_javascript_web(WebSymbolsRegistryImpl.kt:62)
	at com.intellij.javascript.web.symbols.impl.WebSymbolsRegistryImpl.runNameMatchQuery(WebSymbolsRegistryImpl.kt:38)
	at com.intellij.javascript.web.symbols.WebSymbolsRegistry$DefaultImpls.runNameMatchQuery$default(WebSymbolsRegistry.kt:25)
	at com.intellij.javascript.web.codeInsight.html.attributes.WebSymbolAttributeDescriptorsProvider.getAttributeDescriptors(WebSymbolAttributeDescriptorsProvider.kt:25)
	at com.intellij.html.impl.RelaxedHtmlFromSchemaElementDescriptor.addAttrDescriptorsForFacelets(RelaxedHtmlFromSchemaElementDescriptor.java:69)
	at com.intellij.psi.impl.source.html.dtd.HtmlElementDescriptorImpl.getAttributesDescriptors(HtmlElementDescriptorImpl.java:216)
	at com.intellij.psi.impl.source.html.dtd.HtmlNSDescriptorImpl.getCommonAttributeDescriptors(HtmlNSDescriptorImpl.java:74)
	at com.element.xml.ElementAnyXmlElementDescriptor.getAttributesDescriptors(ElementAnyXmlElementDescriptor.java:62)
	at com.element.xml.ElementAnyXmlElementDescriptor.getAttributeDescriptor(ElementAnyXmlElementDescriptor.java:74)
	at com.element.xml.ElementAnyXmlElementDescriptor.getAttributeDescriptor(ElementAnyXmlElementDescriptor.java:68)
	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.getDescriptionImpl(XmlAttributeDelegate.java:68)
	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.lambda$getDescriptor$0(XmlAttributeDelegate.java:55)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.getDescriptor(XmlAttributeDelegate.java:53)
	at com.intellij.psi.impl.source.xml.XmlAttributeImpl.getDescriptor(XmlAttributeImpl.java:191)
	at com.intellij.psi.impl.source.xml.XmlAttributeReference$1.compute(XmlAttributeReference.java:23)
	at com.intellij.psi.impl.source.xml.XmlAttributeReference$1.compute(XmlAttributeReference.java:20)
	at com.intellij.openapi.util.NullableLazyValue.getValue(NullableLazyValue.java:36)
	at com.intellij.psi.impl.source.xml.XmlAttributeReference.getDescriptor(XmlAttributeReference.java:110)
	at com.intellij.psi.impl.source.xml.XmlAttributeReference.resolve(XmlAttributeReference.java:50)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:177)
	at com.intellij.codeInsight.TargetElementUtilBase.doGetReferenceOrReferencedElement(TargetElementUtilBase.java:165)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:204)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:248)
	at com.intellij.codeInsight.TargetElementUtilBase.doFindTargetElement(TargetElementUtilBase.java:227)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:292)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:147)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:174)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:135)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:40)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:22)
	at com.intellij.find.usages.impl.ImplKt.searchTargets(impl.kt:24)
	at com.intellij.find.actions.SearchTargetsDataRule.getData(SearchTargetsDataRule.kt:17)
	at com.intellij.find.actions.SearchTargetsDataRule.getData(SearchTargetsDataRule.kt:11)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRule$4(DataManagerImpl.java:116)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:73)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:52)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataFromProvider$1(DataManagerImpl.java:73)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:68)
	at com.intellij.find.actions.SearchTargetVariantsDataRule.getData(SearchTargetVariantsDataRule.kt:22)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRule$4(DataManagerImpl.java:116)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:73)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getData(PreCachedDataContext.java:126)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.ensureSlowDataKeysPreCached(ActionUpdater.java:355)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$14(ActionUpdater.java:279)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$16(ActionUpdater.java:305)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$17(ActionUpdater.java:305)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$18(ActionUpdater.java:301)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:270)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$19(ActionUpdater.java:300)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:135)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$20(ActionUpdater.java:298)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

![2021-09-07 09 09 30](https://user-images.githubusercontent.com/12215982/132269688-7bbd94bc-3bbb-4afc-a81c-abd4008cb4ff.png)

WebStorm 版本：
![2021-09-07 09 10 01](https://user-images.githubusercontent.com/12215982/132269723-0cfd3e30-b673-4687-9645-e32ce5549e4f.png)

**Comment by besart-rr** [comment]
Unhandled exception in [StandaloneCoroutine{Cancelling}@214eed2b, EdtCoroutineDispatcher@4a68544a]

java.lang.NullPointerException
	at com.element.document.DocumentProvider.generateDoc(DocumentProvider.java:42)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:141)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDoc(PsiElementDocumentationTarget.kt:70)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentation(PsiElementDocumentationTarget.kt:56)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentationAsync$1$documentationResult$1.invoke(impl.kt:25)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentationAsync$1$documentationResult$1.invoke(impl.kt)
	at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
	at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:65)
	at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:12)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$3.run(ReadAction.kt:74)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.openapi.application.rw.ReadAction.tryReadAction(ReadAction.kt:71)
	at com.intellij.openapi.application.rw.ReadAction.access$tryReadAction(ReadAction.kt:14)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2$2.run(ReadAction.kt:62)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2.invokeSuspend(ReadAction.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
