### ISSUE TITLE
webstorm 2022.3--Unable to find template resource: vux;

### ISSUE THREAD

**Issue by Drok1015** [jiaolong1021/ElementPlugin#18]
com.intellij.diagnostic.PluginException: Unable to find template resource: vux; classLoader: PluginClassLoader(plugin=PluginDescriptor(name=element, id=com.shen.plugin.element, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/WebStorm2022.3/plugins/element-2.0.jar, version=2.0, package=null, isBundled=false), packagePrefix=null, instanceId=94, state=active); plugin: PluginInfo(type=LISTED, id=com.shen.plugin.element, version=2.0)
	at com.intellij.codeInsight.template.impl.TemplateSettings.readDefTemplate(TemplateSettings.java:561)
	at com.intellij.codeInsight.template.impl.TemplateSettings.loadDefaultLiveTemplatesFromProvider(TemplateSettings.java:529)
	at com.intellij.codeInsight.template.impl.TemplateSettings.loadDefaultLiveTemplates(TemplateSettings.java:500)
	at com.intellij.codeInsight.template.impl.TemplateSettings.doLoadTemplates(TemplateSettings.java:303)
	at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:283)
	at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:193)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:49)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1002)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:145)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda-1(BaseComponentAdapter.kt:124)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:123)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:92)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:679)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:635)
	at com.intellij.codeInsight.template.impl.TemplateSettings.getInstance(TemplateSettings.java:307)
	at com.intellij.codeInsight.template.impl.LiveTemplatesOptionsTopHitProvider.getOptions(LiveTemplatesOptionsTopHitProvider.java:24)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions$lambda-1(TopHitCache.kt:56)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions(TopHitCache.kt:52)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.getCachedOptions(OptionsTopHitProvider.kt:175)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.cacheAll(OptionsTopHitProvider.kt:138)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.access$cacheAll(OptionsTopHitProvider.kt:1)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity$1.invokeSuspend(OptionsTopHitProvider.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by boson33** [comment]
我也遇到这个问题，什么时候可以解决呀？

**Comment by grafmouse** [comment]
+1
```
com.intellij.diagnostic.PluginException: Unable to find template resource: vux; classLoader: PluginClassLoader(plugin=PluginDescriptor(name=element, id=com.shen.plugin.element, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PhpStorm2022.3/plugins/element-2.0.jar, version=2.0, package=null, isBundled=false), packagePrefix=null, instanceId=106, state=active); plugin: PluginInfo(type=LISTED, id=com.shen.plugin.element, version=2.0)
	at com.intellij.codeInsight.template.impl.TemplateSettings.readDefTemplate(TemplateSettings.java:561)
	at com.intellij.codeInsight.template.impl.TemplateSettings.loadDefaultLiveTemplatesFromProvider(TemplateSettings.java:529)
	at com.intellij.codeInsight.template.impl.TemplateSettings.loadDefaultLiveTemplates(TemplateSettings.java:500)
	at com.intellij.codeInsight.template.impl.TemplateSettings.doLoadTemplates(TemplateSettings.java:303)
	at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:283)
	at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:193)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:49)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:996)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:92)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:673)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
	at com.intellij.codeInsight.template.impl.TemplateSettings.getInstance(TemplateSettings.java:307)
	at com.intellij.codeInsight.template.impl.LiveTemplatesOptionsTopHitProvider.getOptions(LiveTemplatesOptionsTopHitProvider.java:24)
	at com.intellij.ide.ui.TopHitCache$getCachedOptions$1.invoke(TopHitCache.kt:56)
	at com.intellij.ide.ui.TopHitCache$getCachedOptions$1.invoke(TopHitCache.kt:52)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions$lambda$1(TopHitCache.kt:52)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions(TopHitCache.kt:52)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.getCachedOptions(OptionsTopHitProvider.kt:175)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.cacheAll(OptionsTopHitProvider.kt:138)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.access$cacheAll(OptionsTopHitProvider.kt:1)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity$1.invokeSuspend(OptionsTopHitProvider.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by boson33** [comment]
+1

com.intellij.diagnostic.PluginException: Unable to find template resource: vux; classLoader: PluginClassLoader(plugin=PluginDescriptor(name=element, id=com.shen.plugin.element, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\223.8214.51.plugins\element-2.0.jar, version=2.0, package=null, isBundled=false), packagePrefix=null, instanceId=129, state=active); plugin: PluginInfo(type=LISTED, id=com.shen.plugin.element, version=2.0)
	at com.intellij.codeInsight.template.impl.TemplateSettings.readDefTemplate(TemplateSettings.java:561)
	at com.intellij.codeInsight.template.impl.TemplateSettings.loadDefaultLiveTemplatesFromProvider(TemplateSettings.java:529)
	at com.intellij.codeInsight.template.impl.TemplateSettings.loadDefaultLiveTemplates(TemplateSettings.java:500)
	at com.intellij.codeInsight.template.impl.TemplateSettings.doLoadTemplates(TemplateSettings.java:303)
	at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:283)
	at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:193)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:49)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:996)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:92)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:673)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
	at com.intellij.codeInsight.template.impl.TemplateSettings.getInstance(TemplateSettings.java:307)
	at com.intellij.codeInsight.template.impl.LiveTemplatesOptionsTopHitProvider.getOptions(LiveTemplatesOptionsTopHitProvider.java:24)
	at com.intellij.ide.ui.TopHitCache$getCachedOptions$1.invoke(TopHitCache.kt:56)
	at com.intellij.ide.ui.TopHitCache$getCachedOptions$1.invoke(TopHitCache.kt:52)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions$lambda$1(TopHitCache.kt:52)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions(TopHitCache.kt:52)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.getCachedOptions(OptionsTopHitProvider.kt:175)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.cacheAll(OptionsTopHitProvider.kt:138)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.access$cacheAll(OptionsTopHitProvider.kt:1)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity$1.invokeSuspend(OptionsTopHitProvider.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by OldKroll** [comment]
+1
com.intellij.diagnostic.PluginException: Unable to find template resource: vux; classLoader: PluginClassLoader(plugin=PluginDescriptor(name=element, id=com.shen.plugin.element, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/WebStorm2022.3/plugins/element-2.0.jar, version=2.0, package=null, isBundled=false), packagePrefix=null, instanceId=107, state=active); plugin: PluginInfo(type=LISTED, id=com.shen.plugin.element, version=2.0)
	at com.intellij.codeInsight.template.impl.TemplateSettings.readDefTemplate(TemplateSettings.java:561)
	at com.intellij.codeInsight.template.impl.TemplateSettings.loadDefaultLiveTemplatesFromProvider(TemplateSettings.java:529)
	at com.intellij.codeInsight.template.impl.TemplateSettings.loadDefaultLiveTemplates(TemplateSettings.java:500)
	at com.intellij.codeInsight.template.impl.TemplateSettings.doLoadTemplates(TemplateSettings.java:303)
	at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:283)
	at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:193)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:49)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:996)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:92)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:673)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
	at com.intellij.codeInsight.template.impl.TemplateSettings.getInstance(TemplateSettings.java:307)
	at com.intellij.codeInsight.template.impl.LiveTemplatesOptionsTopHitProvider.getOptions(LiveTemplatesOptionsTopHitProvider.java:24)
	at com.intellij.ide.ui.TopHitCache$getCachedOptions$1.invoke(TopHitCache.kt:56)
	at com.intellij.ide.ui.TopHitCache$getCachedOptions$1.invoke(TopHitCache.kt:52)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions$lambda$1(TopHitCache.kt:52)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions(TopHitCache.kt:52)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.getCachedOptions(OptionsTopHitProvider.kt:175)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.cacheAll(OptionsTopHitProvider.kt:138)
	at com.intellij.ide.ui.OptionsTopHitProviderKt.access$cacheAll(OptionsTopHitProvider.kt:1)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity$1.invokeSuspend(OptionsTopHitProvider.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
